### ISSUE TITLE
Update symfony/property-access dependency in composer.json to version 4

### ISSUE THREAD

**Issue by mutaboricha** [academe/Omnipay-AuthorizeNetApi#10]
Could you update the symfony/property-access dependency from 3 to 4?

**Comment by judgej** [comment]
If it works the same, we could set the dependency to 3 *or* 4. Would that work?

**Comment by mutaboricha** [comment]
If you look at the documentation, it did not change as it was at 3, and it remained at 4. They are fully compatible with interfaces and namespaces. Version 3 uses older php versions.

**Comment by judgej** [comment]
Cool, we'll do that then. It does have to work over a range of frameworks that all have their own needs, so should be as flexible as possible. Also I appreciate there may be some urgency, what with the deprecated md5 signatures disappearing completely in a few weeks, so there could be a panic on to upgrade Authorize.Net drivers across many sites.

If you have a PR we can use, that would be helpful to speed this up. `"~3|~4"` or something, I suspect.

**Comment by judgej** [comment]
With the additional support, `composer update` gave me this:

```text
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 2 removals
  - Removing symfony/polyfill-php70 (v1.10.0)
  - Removing paragonie/random_compat (v9.99.99)
  - Updating symfony/property-access (v3.4.22 => v4.2.3): Downloading (100%)
```

Unit tests (what that there are) look good to me. Sandbox tests (direct, hosted payment page and accept.js) all work for me unchanged.

**Comment by mutaboricha** [comment]
Thanks
