### ISSUE TITLE
UserFields not working

### ISSUE THREAD

**Issue by alpeshsavalia** [academe/Omnipay-AuthorizeNetApi#13]
Hi There,

I'm passing the UserFields with authorize API call. but I can't get it in response.
![image](https://user-images.githubusercontent.com/19701155/59959355-39c91300-94d3-11e9-83fe-c9a787d57a5d.png)

anything I'm doing wrong ? which fields should i use to post the UserFields ?

Can you help me to check it ?

Thanks.

**Comment by judgej** [comment]
You weren't doing anything wrong - user fields were not supported.

I've made a quick change on branch `issue13` that allows user fields to be sent using the format you have given, except you must remove the "userField" key. You may also use key value pairs, so either of these will work:

```php
    'userFields' => [
        'foo' => 'bar',
        [
            'name' => 'Test',
            'value' => 'Test111',
        ]
    ],
```
I have just tried this with the Hosted Page API, and see the fields in the merchant email:

```text
========== MERCHANT DEFINED =========
x_customer_type : individual
foo : bar
Test : Test111
```

Could you try that branch and see if it works for you. I haven't tried the other APIs yet, but it should work.  I just had half an hour to knock this together, and will finish it off during the week, with some documentation, with your help.

**Comment by alpeshsavalia** [comment]
ok great, thanks

**Comment by judgej** [comment]
You'll need to update `academe/authorizenet-objects` too, as this involves a small fix to that package.

**Comment by marcusmoore** [comment]
Hello,

I just double-checked the `issue13` branch using the `purchase` method and both the `name/value` and key-pair syntax worked for me.

Is there anything I can help with to get this pulled in?

Thanks!

**Comment by judgej** [comment]
I've merged and tagged for release. Apologies for the stupid delay - just trying to keep my eyes on too many balls. If you could confirm release 3.1.2 works, please go ahead and close this issue. Thank you.

**Comment by alpeshsavalia** [comment]
ok , I will check it. thanks for your support.

**Comment by marcusmoore** [comment]
> Apologies for the stupid delay

No worries @judgej. Everything looks like it's working. Thanks!
