### ISSUE TITLE
Difficulty with CIM gateway createCard method

### ISSUE THREAD

**Issue by paxperscientiam** [academe/Omnipay-AuthorizeNetApi#19]
Hello!

I'm having some difficulty with the createCard method. It works just fine for new customers: it will create both a new customer profile and an associate customer payment profile. However, it will not add new payment profiles to an existing customer profile. Instead, the response says the customer record already exists.

I'm doing the above with opaque data. I'd like to do the same for adding new payment profiles to existing customer profiles. Is not not possible with the createCard method?

EDIT: I should add, ANY insight would be appreciated.

EDIT2: https://github.com/thephpleague/omnipay-authorizenet/pull/121 seems related

EDIT3: Got it. For anyone else, it's `createAdditionalCard()` on the CIM gateway.

Thanks

here's a relevant snippet:
```
	$payload = [
			"opaqueDataDescriptor" => $data['dataDescriptor'],
			"opaqueDataValue" => $data['dataValue'],
			"name" => $this->user_model->fullname,
			"email" => $this->user_model->email,
			'customerType' => 'individual',
			"customerId" => 'M_'.$this->user_model->id,
			"description" => "...",
			'forceCardUpdate' => true,
			'card' => [
				'billingFirstName' => $address_model->firstname,
				'billingLastName' => $address_model->lastname,
				'billingAddress1' => $address_model->address_line1,
				'billingAddress2' => $address_model->address_line2,
				'billingCity' => $address_model->city,
				'billingState' => $address_model->state,
				'billingPostcode' => $address_model->zip,
				'billingCountry' => $address_model->country
			]
		];

		$customerProfileId = empty($this->user_model->authorizenet_customer_id) ? NULL : $this->user_model->authorizenet_customer_id;
	
		if (null != $customerProfileId) {
			//	$payload["customerProfileId"] = $customerProfileId;
		}

		$request = $this->gateway_CIM->createCard($payload);

		if (null != $paymentProfileId) {
			$request->setCustomerPaymentProfileId($paymentProfileId);
		}

		try {
			$response = $request->send();
...
```

**Comment by sgtcoder** [comment]
Are we not able to create customer/card using CIM with this API?
