### ISSUE TITLE
How do I set the rest of the Customer object?

### ISSUE THREAD

**Issue by nickmoline** [academe/Omnipay-AuthorizeNetApi#8]
Seems that the only part of the Customer Model you populate is the email address, even though there's other attributes in your model and common ways in omnipay to send them

https://github.com/academe/omnipay-authorizenetapi/blob/master/src/Message/AuthorizeRequest.php#L90

https://github.com/academe/authorizenet-objects/blob/master/src/Request/Model/Customer.php

In particular I need to be able to set Customer->id (normally in omnipay, including in your AIM/SIM version) you set this with `customerId` key in the array sent to the purchase method.

Your other gateway for the AIM/SIM integration method you accept customerId, why not in the API version?
https://github.com/thephpleague/omnipay-authorizenet/blob/c109d81bc2cdbee8705fe9e4f99ba55841485286/src/Message/AIMAbstractRequest.php#L298

**Comment by judgej** [comment]
This was a noted TODO, now done in the master branch if you want to give it a go. I've a few more tweaks to do before releasing this.

**Comment by judgej** [comment]
This is now in release 3.0.5. Please let me know if there are any issues with it.

**Comment by nickmoline** [comment]
Works great, thanks for taking care of this so quickly

**Comment by judgej** [comment]
No problem :-) With DPM being deprecated for a while, I need to ramp up development on this driver a little, as I have a few sites that need to switch over from the legacy Omnipay driver, so this was a timely reminder.

**Comment by judgej** [comment]
Closing as now live and confirmed, thank you.
